version: '3'

services:
  deepseek-free-api:
    container_name: deepseek-free-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Shanghai
